#!/bin/bash
# Check if httpd is installed
httpd -v > /dev/null 2>&1
if [ $? -eq 0 ]
then
    echo "httpd is installed, stopping service."
    sudo service httpd stop
else
    echo "httpd not found. No need to stop service."
fi
